package test2.bean;

// Generated 2016-6-2 14:50:55 by Hibernate Tools 3.4.0.CR1

/**
 * LJuser generated by hbm2java
 */
public class LJuser implements java.io.Serializable {

    private int id;
    private Integer age;
    private String name;

    public LJuser() {
    }

    public LJuser(int id) {
        this.id = id;
    }

    public LJuser(int id, Integer age, String name) {
        this.id = id;
        this.age = age;
        this.name = name;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "LJuser [id=" + id + ", age=" + age + ", name=" + name + "]";
    }
    

}
