package test2.bean;

// Generated 2016-6-2 14:50:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TBusiApprTdEventRules generated by hbm2java
 */
public class TBusiApprTdEventRules implements java.io.Serializable {

    private String uuid;
    private String loanid;
    private String policyUuid;
    private String decision;
    private BigDecimal score;
    private String name;

    public TBusiApprTdEventRules() {
    }

    public TBusiApprTdEventRules(String uuid, String loanid, String policyUuid) {
        this.uuid = uuid;
        this.loanid = loanid;
        this.policyUuid = policyUuid;
    }

    public TBusiApprTdEventRules(String uuid, String loanid, String policyUuid, String decision, BigDecimal score, String name) {
        this.uuid = uuid;
        this.loanid = loanid;
        this.policyUuid = policyUuid;
        this.decision = decision;
        this.score = score;
        this.name = name;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getLoanid() {
        return this.loanid;
    }

    public void setLoanid(String loanid) {
        this.loanid = loanid;
    }

    public String getPolicyUuid() {
        return this.policyUuid;
    }

    public void setPolicyUuid(String policyUuid) {
        this.policyUuid = policyUuid;
    }

    public String getDecision() {
        return this.decision;
    }

    public void setDecision(String decision) {
        this.decision = decision;
    }

    public BigDecimal getScore() {
        return this.score;
    }

    public void setScore(BigDecimal score) {
        this.score = score;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
