package test2.bean;

// Generated 2016-6-2 14:50:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TBusiApprTdEvent generated by hbm2java
 */
public class TBusiApprTdEvent implements java.io.Serializable {

    private String keyno;
    private String loanid;
    private String policyUuid;
    private String policyDecision;
    private BigDecimal policyScore;
    private String policyName;
    private String riskType;

    public TBusiApprTdEvent() {
    }

    public TBusiApprTdEvent(String keyno, String loanid) {
        this.keyno = keyno;
        this.loanid = loanid;
    }

    public TBusiApprTdEvent(String keyno, String loanid, String policyUuid, String policyDecision, BigDecimal policyScore, String policyName,
            String riskType) {
        this.keyno = keyno;
        this.loanid = loanid;
        this.policyUuid = policyUuid;
        this.policyDecision = policyDecision;
        this.policyScore = policyScore;
        this.policyName = policyName;
        this.riskType = riskType;
    }

    public String getKeyno() {
        return this.keyno;
    }

    public void setKeyno(String keyno) {
        this.keyno = keyno;
    }

    public String getLoanid() {
        return this.loanid;
    }

    public void setLoanid(String loanid) {
        this.loanid = loanid;
    }

    public String getPolicyUuid() {
        return this.policyUuid;
    }

    public void setPolicyUuid(String policyUuid) {
        this.policyUuid = policyUuid;
    }

    public String getPolicyDecision() {
        return this.policyDecision;
    }

    public void setPolicyDecision(String policyDecision) {
        this.policyDecision = policyDecision;
    }

    public BigDecimal getPolicyScore() {
        return this.policyScore;
    }

    public void setPolicyScore(BigDecimal policyScore) {
        this.policyScore = policyScore;
    }

    public String getPolicyName() {
        return this.policyName;
    }

    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }

    public String getRiskType() {
        return this.riskType;
    }

    public void setRiskType(String riskType) {
        this.riskType = riskType;
    }

}
